### ISSUE TITLE
Frontier Calculation Incorrect

### ISSUE THREAD

**Issue by bpfarmer** [agglayer/agglayer#184]
After this [discussion](https://github.com/orgs/agglayer/discussions/119#discussioncomment-10127970) I think that there may be some issues with recalculating the frontier.

My understanding is that the frontier should be the set of roots of the maximal power-of-2-sized subtrees and the frontier array should have length corresponding to the max tree depth. This is the minimal information required to append new leaves to the tree. 

Some examples (for a tree of max size 8, where h is the node with children given by the subscript, the index of `frontier` is the leaf count, and the leaf indices begin with `1`):

`frontier_1 = [h_1, 0, 0, 0]`
`frontier_5 = [h_5, 0, h_1234, 0]`
`frontier_6 = [0, h_56, h_1234, 0]`
`frontier_8 = [0, 0, 0, h_12345678]`

However, when we look at the [code](https://github.com/agglayer/agglayer/blob/bdf26d30db51385e1466c927b2d396bec9d0b384/crates/pessimistic-proof/src/local_exit_tree/mod.rs#L69), it looks like the frontier isn't being calculated correctly.

For `n=1`, `frontier_insertion_index=2`, `entry=h_2`, so we have:

`entry = H(h_1, h_2)` <- `h_12`
`entry = H(0, h_12)` <- Incorrect

`frontier_2` should be set to `[0, h_12, 0, 0]`. We need to clear entries in the frontier when we add a leaf that results in a completed subtree, and the new frontier entries should be calculated correctly.

**Comment by wborgeaud** [comment]
Hm if `n=1` represents the number of leafs before insertion, then `frontier_insertion_index=1`, and so we just get the correct
```
entry = H(h_1, h_2) (= h_12)
```
`frontier_2` is then `[h_1, h_12, 0, 0]`, and while the `h_1` at index 0 isn't technically correct, it's not actually used anywhere, in particular when calling `get_root`. So I think it's fine not to clean the unused entries in the frontier.

**Comment by HarryTmetic** [comment]
There is no need to clear entries, because given the `leaf_count` the entries corresponding to 0s will be "discarded", it allows to write only once per newly appended leaf. This is why my calculation of the frontier is the other discussion doesn't have 0s where yours has, because it is unnecessary. By looking at the leaf count we have all the information needed.

**Comment by bpfarmer** [comment]
> Hm if n=1 represents the number of leafs before insertion, then frontier_insertion_index=1, and so we just get the correct

@wborgeaud if you look at [this](https://github.com/agglayer/agglayer/blob/bdf26d30db51385e1466c927b2d396bec9d0b384/crates/pessimistic-proof/src/local_exit_tree/mod.rs#L60C13-L60C66) the author increments `frontier_insertion_index` so it's 2 - that's why I included the second line.

**Comment by wborgeaud** [comment]
> @wborgeaud if you look at [this](https://github.com/agglayer/agglayer/blob/bdf26d30db51385e1466c927b2d396bec9d0b384/crates/pessimistic-proof/src/local_exit_tree/mod.rs#L60C13-L60C66) the author increments `frontier_insertion_index` so it's 2 - that's why I included the second `entry`.

Maybe I'm missing something obvious, but in the code you link we get `leaf_count_after_insertion = self.leaf_count + 1 = 2` and `frontier_insertion_index = leaf_count_after_insertion.trailing_zeros() = 2.trailing_zeros() = 1`.

**Comment by bpfarmer** [comment]
Ahh my mistake - I didn't see the trailing zeros - you're right.

**Comment by bpfarmer** [comment]
@HarryTmetic yeah that's true - though to be fair it's a bit simpler with unnecessary entries removed and you don't need `leaf_count`. 

We would've maybe saved some discussion about `leaf_count_a` vs `leaf_count_a - 1` as it's very obvious that the binary decomposition of `leaf_count_a` maps to non-zero (or necessary) entries of the frontier.
