### ISSUE TITLE
When settling on L1, the trusted sequencer address need to be used in place of the ProofSigner one

### ISSUE THREAD

**Issue by Freyskeyd** [agglayer/agglayer#212]
When creating the contract call for L1, and if a `ProofSigner` is defined, the `beneficiary` should be the `trusted sequencer` address.

We should also investigate how to remove the `ProofSigner` from the config, having something more decentralized.

**Comment by Sharonbc01** [comment]
Hi @Freyskeyd wanted to ask you do you have any ETA on this issue?

**Comment by Sharonbc01** [comment]
ETA shared back is around end of august/beginning of September
