### ISSUE TITLE
Review RPC timeouts

### ISSUE THREAD

**Issue by iljakuklic** [agglayer/agglayer#230]
The Agglayer node connects to various other services via RPC, most notably the L1 node and L2 nodes. The L2 queries are used to obtain the current state roots. There should be a sensible timeout if an RPC call to any of these gets stuck.

This applies to:
* Agglayer <-> L1 node communication
* Agglayer <-> L2 nodes communication
* Agglayer <-> proof generation service communication

As noted by @praetoriansentry:

> Agglayer needs time outs - is it just waiting forever right now? This should have been picked up in reliability / chaos testing... which we never did.

This may result in the `sendTx` call being stuck rather than returning an error. If the client just disconnects, it is not obvious how to diagnose the issue.

**Comment by iljakuklic** [comment]
I took a look at how the Agglayer <-> L2 nodes RPC communication is done. Initial investigation suggests there is the default `jsonrpsee` timeout of 60 seconds. This is not currently configurable.

The reason we have not seen (and logged) the timeout error is (most likely) that the request was dropped before the timeout had the chance to occur as described in #231.

**Comment by Freyskeyd** [comment]
Yes, the default value is 60sec for every RPCs that use `Http` client of `jsonrpsee`. We can configure this with this [method](https://docs.rs/jsonrpsee-http-client/0.24.3/jsonrpsee_http_client/struct.HttpClientBuilder.html#method.request_timeout).

**Comment by iljakuklic** [comment]
Continuing investigation... for contacting the L1 node, the `Http` provider from the `ethers` library is used with default settings. Timeouts are handled by the underlying library which in this case is `reqwest`. By default, the `reqwest::Client` imposes **no timeout** on the duration of a request. This could be changed by creating the `reqwest::Client` object manually with appropriate options and passing it to the ethers provider upon construction.

**Comment by iljakuklic** [comment]
As for the proof generation service, it's not quite clear to me what will be used in the end so there's not much to say about it at the moment.

**Comment by iljakuklic** [comment]
For completeness. The RPC server implementation that handles the RPC calls to the Agglayer node is `jsonrpsee`. It is possible to impose timeout for the duration of any request served by the agglayer node. It can be done by adding the `timeout` layer to the http middleware when building the RPC server object. It is demonstrated [in the docs for the `ServerBuilder::set_middleware` function](https://docs.rs/jsonrpsee-server/0.24.3/jsonrpsee_server/struct.ServerBuilder.html#method.set_http_middleware).

This is currently not done so no timeouts on the overall request serving time either.

**Comment by iljakuklic** [comment]
We are only making trivial calls, especially to the L2 nodes. I think it would make sense to decrease the request timeouts to say 30s. That would make implementing #231 less pressing. Thoughts/comments?
