### ISSUE TITLE
[audit] keccak256_combine is not a safe generic hashing function

### ISSUE THREAD

**Issue by tob-joe** [agglayer/agglayer#234]
Severity: Informational
Difficulty: Not Applicable
Type: Cryptography
Target: crates/pessimistic-proof/src/keccak.rs

## Description
The function `keccak256_combine`, shown below, returns a hash of an array of values.
https://github.com/agglayer/agglayer/blob/d9d33885b6a396a69f57054d7b549edc6ca1ef51/crates/pessimistic-proof/src/keccak.rs#L40-L54
Although it is generic over the type parameter `T`, `keccak256_combine` is not guaranteed to be collision-resistant for sequences when `T` has values with different byte-lengths, due to ambiguous encodings. For example, the following test, where `T` is `Vec<u8>`, fails:
```rs
#[test]
fn test_keccak256_combine_collision() {
    assert_ne!(keccak256_combine(vec![vec![0,1],vec![2]]),
               keccak256_combine(vec![vec![0],vec![1,2]]))
}
```

This construction is an example of [the YoloMultiHash ad-hoc hash construction](https://blog.trailofbits.com/2024/08/21/yolo-is-not-a-valid-hash-construction/), which is unsafe when fields of the data structure can overlap, thus leading to hash values for semantically different inputs.

We have not discovered any current uses of `keccak256_combine` in the `pessimistic-proof` crate which are vulnerable due to this issue. Most inputs are implicitly protected because they have fixed lengths. For example, the `BridgeExit` hash has a fixed input length of 85 bytes, even though it uses `keccak256_combine` where `T` is the variable-length type `[u8]` https://github.com/agglayer/agglayer/blob/d9d33885b6a396a69f57054d7b549edc6ca1ef51/crates/pessimistic-proof/src/bridge_exit.rs#L101-L112

## Recommendations
Short term, review all use of `keccak256_combine` to ensure unambiguous encodings. Consider modifying `keccak256_combine` to generically ensure unambiguous encoding. For example, by restricting `T` to fixed-size types or prefixing each entry with its length.

Long term, consider adopting standard schemes for hashing structured data, e.g. TupleHash.

## References
[“YOLO” is not a valid hash construction](https://blog.trailofbits.com/2024/08/21/yolo-is-not-a-valid-hash-construction/)

**Comment by wborgeaud** [comment]
Added a comment regarding the safety of `keccak256_combine` in #256. 
I don't think we'll ever need to hash variable length data in this crate, so I think it's fine to keep `keccak256_combine` as is and just make sure it's always used safely.
