### ISSUE TITLE
[audit] `get_inclusion_proof_zero` overwrites nonzero entries

### ISSUE THREAD

**Issue by tob-joe** [agglayer/agglayer#238]
Severity: Informational
Difficulty: Not Applicable
Type: Testing
Target: crates/pessimistic-proof/src/util/smt.rs

## Description
Calling the method `get_inclusion_proof_zero` on a key with a nonzero value will set that value to zero, and return an inclusion proof in a different tree.

https://github.com/agglayer/agglayer/blob/d9d33885b6a396a69f57054d7b549edc6ca1ef51/crates/pessimistic-proof/src/utils/smt.rs#L248-L263

The correct version of the hack described in the comment would instead call `insert_helper` directly with the `update` parameter set to `false`.

Currently this method is only used in a test function which only calls it when the value is already known to be zero, but public data structure methods such as this should be tested for correct behavior in a wide range of uses. This behavior would be caught by a test that ensures that `get_inclusion_proof_zero` never changes the root hash of the tree.

## Recommendations
Short term, fix this function and add a regression test.

Long term, ensure that all public API functions are thoroughly tested.

**Comment by wborgeaud** [comment]
Fixed in #245 by using `insert` instead of `update`.
