### ISSUE TITLE
[audit] `apply_batch_header` mutates local state on error return

### ISSUE THREAD

**Issue by tob-joe** [agglayer/agglayer#239]
Severity: Informational
Difficulty: Not Applicable
Type: Error Reporting
Target: crates/pessimistic-proof/src/local_state.rs

## Description
Multi-Batches are simultaneously validated and applied to a local state by the `apply_batch_header` method. However, the method mutates the state as it goes, before fully validating the multi-batch. When this method returns `Err`, the state is left with an invalid operation partially applied to its data structures.

This behavior is misuse-prone, and contradicts the current documentation on the method signature:
https://github.com/agglayer/agglayer/blob/d9d33885b6a396a69f57054d7b549edc6ca1ef51/crates/pessimistic-proof/src/local_state.rs#L35-L40

To prevent accidental use of these invalid states, callers must either ensure that an error return destroys the state on error, or that the previous state is preserved and can be restored. Although all current uses fall into one of these two approaches, we would encourage modifying the method to be misuse-resistant.

## Recommendations
Short term, modify the implementation either to do roll-backs  or destruction on error internally. A roll-back version could consist of moving the current `apply_batch_header` into a helper function and calling that with a local cloned variable, only updating `self` on success. A destruction version would take `self` instead of `&mut self` and return `Result<Self, ProofError>` — the partially-modified version would simply be destroyed in the case of an error return.

Long term, document the required usage of all core validation functions. Whenever possible, design APIs to reject improper or unsafe usage as early as possible — ideally at compile-time with misuse-resistant type signatures.

**Comment by wborgeaud** [comment]
Fixed in #247 by using the roll-back version.
