### ISSUE TITLE
aggLayer to verify finality on `l1InfoTreeRoot`

### ISSUE THREAD

**Issue by krlosMata** [agglayer/agglayer#304]
# Rationale
`aggLayer` should run its own l1InfoTreeRoot synchronizer in order to know if the `l1InfoRoot` sent by a chain is finalized on Ethereum.
This should be done in order to:
- not trust `l1InfotreeRoots` sent by the chains
- avoid computing proofs that may not be settled to L1 due to L1 reorgs
- re-sent and re-compute same certificate twice in case in invalid due to reorg on the `l1InfoTreeRoot` param

**Comment by Freyskeyd** [comment]
This is addressed in a Design ticket.
Closing this one in favor of the design ticket
