### ISSUE TITLE
Integrate `pessimistic-proof` in `agglayer-rs`

### ISSUE THREAD

**Issue by pgebheim** [agglayer/agglayer#52]
As part of generating a batch a pessimistic proof should be across all the new batch updates.

AggLayer-rs will also need configurations to override/set API keys, set whether to prove locally or use remote infra.

- [x] Having the `pessimistic-proof` logic in the `agglayer` 
   - https://github.com/agglayer/agglayer/pull/100
- [x] Adapting the PP API to feed the right inputs
   - #104 
- [x] Setup for SP1 while giving the proving type among [local, network, mock] 
   - #144 
- [x] Minimal state management to track the state and feed the right inputs into the PP
   - #78 
   - #172

**Comment by Freyskeyd** [comment]
On a wider view, I think both repo should be merged.

**Comment by pgebheim** [comment]
Monorepo time?

**Comment by Freyskeyd** [comment]
@pgebheim I believe that it would make more sense to have that yes.
What do you think?

**Comment by muursh** [comment]
@Freyskeyd I think it makes sense. Feel free to go ahead and do it
