### ISSUE TITLE
AggLayer-rs Deployment

### ISSUE THREAD

**Issue by pgebheim** [agglayer/agglayer#53]
Details being tracked:
https://docs.google.com/spreadsheets/d/1eT3ZLfR1UQK1IwA0xbamCMA6cSQpvF_XDojBNVdGZTo/edit#gid=2029414957

**Comment by Freyskeyd** [comment]
Docker images are available and can be built for further needs.
The parity version is tagged as `v0.1.0`, the next version, supporting the epochs and such will be tagged `v1.0.0`.

If issues are related to `v0.1.0` and need to be addressed, a dedicated branch can be created and the different changes can be backport to `main` if needed.

**Comment by Freyskeyd** [comment]
This current issue is on hold, waiting for the devops team to have a little bandwidth to iterate 🙏
