### ISSUE TITLE
Use Pessimistic Proof to gate settlement for chains without executions proofs

### ISSUE THREAD

**Issue by pgebheim** [agglayer/agglayer#56]
A chain with the pessimistic rollupType will have a consensus verifier that can accept the pessimistic proof instead of an execution proof. We need to handle this case such that the AggLayer is able to direct the right proofs to the right verifier.

This is related to #55 since there will be other information to pass along to this verifier.

**Comment by krlosMata** [comment]
- SP1 verifier should be selected when adding a new rollupType:
  - https://github.com/0xPolygonHermez/zkevm-contracts/blob/feature/ongoingPP/contracts/v2/PolygonRollupManager.sol#L418
- Program execution identifier `programVKey` must be also specififed:
  - https://github.com/0xPolygonHermez/zkevm-contracts/blob/feature/ongoingPP/contracts/v2/PolygonRollupManager.sol#L423

**Comment by Freyskeyd** [comment]
Closing as it has been done or replace by other ticket
