### ISSUE TITLE
End-to-End Tests on Succint Infra

### ISSUE THREAD

**Issue by pgebheim** [agglayer/agglayer#79]
We need to run the proover run in an end-to-end environment on the succinct infrastructure.

Thoughts:
- Basic unit-test style
- Load Tests (on demand?)
- Catch error cases and assert we can handle them

How to handle:
- Fallbacks, what happens if they don't respond?
- How much load can it handle, does this meet our expectations?

**Comment by Freyskeyd** [comment]
I started a [PR](https://github.com/AggLayer/agglayer-rs/pull/82) regarding the SP1 integration.

If we use different kind of `Prover` such as [local](https://github.com/succinctlabs/sp1/blob/main/sdk/src/provers/local.rs#L12), [mock](https://github.com/succinctlabs/sp1/blob/main/sdk/src/provers/mock.rs#L15) and [network](https://github.com/succinctlabs/sp1/blob/main/sdk/src/network/prover.rs#L19).

Network prover could be configured for both load-e2e tests on demand and production while local/mock for other kind of tests to keep agglayer isolated from network calls.
